# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PowerSet <- function(iK) {
    .Call('eDMA_PowerSet', PACKAGE = 'eDMA', iK)
}

funcEstimate_Eff <- function(vY, mX, vDelta, dAlpha, vKeep, bZellnerPrior = TRUE, dG = 50.0) {
    .Call('eDMA_funcEstimate_Eff', PACKAGE = 'eDMA', vY, mX, vDelta, dAlpha, vKeep, bZellnerPrior, dG)
}

funcEstimate_Eff_par <- function(vY, mX, vDelta, dAlpha, vKeep, bZellnerPrior = TRUE, dG = 50.0, iCores = 2L) {
    .Call('eDMA_funcEstimate_Eff_par', PACKAGE = 'eDMA', vY, mX, vDelta, dAlpha, vKeep, bZellnerPrior, dG, iCores)
}

SimulateDLM <- function(iT, mX, vBeta0, mW, dV, dPhi) {
    .Call('eDMA_SimulateDLM', PACKAGE = 'eDMA', iT, mX, vBeta0, mW, dV, dPhi)
}

